# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('starttime', models.DecimalField(decimal_places=2, max_digits=5)),
                ('t1', models.CharField(max_length=200)),
                ('t2', models.CharField(max_length=200)),
                ('t3', models.CharField(max_length=200)),
                ('t4', models.CharField(max_length=200)),
                ('t5', models.CharField(max_length=200)),
                ('t6', models.CharField(max_length=200)),
                ('t7', models.CharField(max_length=200)),
                ('t8', models.CharField(max_length=200)),
                ('t9', models.CharField(max_length=200)),
                ('t10', models.CharField(max_length=200)),
                ('t11', models.CharField(max_length=200)),
                ('t12', models.CharField(max_length=200)),
                ('t13', models.CharField(max_length=200)),
                ('t14', models.CharField(max_length=200)),
                ('t15', models.CharField(max_length=200)),
                ('t16', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('topbranch', models.CharField(max_length=200)),
                ('next', models.CharField(max_length=200)),
                ('previous', models.CharField(max_length=200)),
                ('startdate', models.DateField()),
                ('stopdate', models.DateField()),
                ('treevalue', models.IntegerField(default=0)),
                ('progressvalue', models.IntegerField(default=0)),
                ('audio', models.FileField(blank=True, upload_to='goal/media')),
            ],
        ),
    ]
