# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0002_auto_20160810_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='priority',
        ),
        migrations.AlterField(
            model_name='day',
            name='starttime',
            field=models.TimeField(),
        ),
    ]
